const captureWebsite = require('capture-website');
const fs = require('fs');
let date = new Date();
// create a new folder 
let dir = `captures/${date.getFullYear()}${date.getMonth()<10 ? '0' : '' }${date.getMonth()+1}${date.getDate()}_${date.getHours()}${date.getMinutes()<10 ? '0' : '' }${date.getMinutes()}`;
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true});
}


let siteList = [["1.usa.gov","FAS TTS/SOL"],
["10x.gsa.gov","FAS TTS/SOL"],
["18f.gsa.gov","FAS TTS/18F"],
["8astars.fas.gsa.gov","FAS ESM"],
["aas.gsa.gov","FAS AAS"],
["accessibility.18f.gov","FAS TTS/18F"],
["accessibility.digital.gov","FAS TTS/SOL"],
["acquisition.gov","OGP MV"],
["agile-labor-categories.18f.gov","FAS TTS/18F"],
["agile.18f.gov","FAS TTS/18F"],
["all-sorns.app.cloud.gov","FAS TTS/18F"],
["amp.fas.gsa.gov","FAS QQA"],
["analytics.usa.gov","FAS TTS/SOL"],
["api.code.gov","FAS TTS/SOL"],
["api.data.gov","FAS TTS/SOL"],
["api.usa.gov","FAS TTS/SOL"],
["app.cloud.gov","FAS QQ2"],
["app.markryan.identitysandbox.gov","FAS TTS/SOL"],
["apps.ocfo.gsa.gov","GSA IT"],
["arch.idmanagement.gov","OGP ME"],
["arm.fas.gsa.gov","FAS"],
["asis.search.usa.gov","FAS TTS/SOL"],
["ask.gsa.gov","FAS CASE"],
["atf-eregs.18f.gov","FAS TTS/18F"],
["autoauctions.gsa.gov","FAS"],
["autovendor.fas.gsa.gov","FAS TTL"],
["before-you-ship.18f.gov","FAS TTS/18F"],
["beta.SAM.gov","FAS OSM/IAE"],
["blog.usa.gov","FAS TTS/SOL"],
["brand.18f.gov","FAS TTS/18F"],
["brody.identitysandbox.gov","FAS TTS/SOL"],
["calc.gsa.gov","FAS OESM"],
["cao.gov","OGP MV"],
["cars.fas.gsa.gov","FAS TTL"],
["catalog-next.data.gov","FAS TTS/SOL"],
["catalog.data.gov","FAS TTS/SOL"],
["cfo.gov","OGP MY"],
["challenge.gov","FAS TTS/SOL"],
["chat.18f.gov","FAS TTS/SOL"],
["ci.identitysandbox.gov","FAS TTS/SOL"],
["cio.gov","OGP MY"],
["citizenscience.gov","FAS TTS/SOL"],
["cloud.cio.gov","OGP MY"],
["cloud.gov","FAS TTS/SOL"],
["cm-jira.usa.gov","GSA IT"],
["cmls.gsa.gov","FAS R5"],
["code.gov","FAS TTS/SOL"],
["coe.gsa.gov","FAS TTS/COE"],
["computersforlearning.gov","FAS GSS"],
["conectate.gobiernousa.gov","FAS TTS/SOL"],
["connect.digita.gov","FAS TTS/SOL"],
["connect.usa.gov","FAS TTS/SOL"],
["content-guide.18f.gov","FAS TTS/18F"],
["content.fai.gov","OGP"],
["contractdirectory.gov","FAS"],
["corporateapps.gsa.gov","GSA IT"],
["cpars.gov","FAS OSM/IAE"],
["cpsearch.fas.gsa.gov","FAS TTL"],
["crime-data-explorer.fr.cloud.gov","FAS TTS/SOL"],
["crissupb.identitysandbox.gov","FAS TTS/SOL"],
["d2d.gsa.gov","GSA IT IDM"],
["dap.digita.gov","FAS TTS/SOL"],
["dashboard.brody.identitysandbox.gov","FAS TTS/SOL"],
["dashboard.markryan.identitysandbox.gov","FAS TTS/SOL"],
["data.gov","FAS TTS/SOL"],
["datacenters.cio.gov","OGP MY"],
["derisking-guide.18f.gov","FAS TTS/18F"],
["designsystem.digital.gov","FAS TTS/SOL"],
["dev.identitysandbox.gov","FAS TTS/SOL"],
["developers.login.gov","FAS TTS/SOL"],
["devicepki.idmanagement.gov","OGP ME"],
["digital.gov","FAS TTS/SOL"],
["digitaldashboard.gov","OGP ME"],
["discovery.gsa.gov","FAS PSHC"],
["disposal.gsa.gov","PBS"],
["domains.do.gov","OGP ME"],
["drivethru.gsa.gov","FAS TTL"],
["ebuy.gsa.gov","FAS MAS"],
["eng-hiring.18f.gov","FAS TTS/18F"],
["engineering.18f.gov","FAS TTS/18F"],
["eoffer.gsa.gov","FAS MAS"],
["esrs.gov","FAS OSM/IAE"],
["extportal.pbs.gsa.gov","PBS"],
["facadatabase.gov","OGP MA"],
["fai.gov","OGP MV"],
["fairs.reporting.gov","OGP MA"],
["fapiis.gov","FAS OSM/IAE"],
["faq.coronavirus.gov","FAS TTS/COE"],
["fdms.gov","OGP MR"],
["federalist-builder.18f.gov","FAS TTS/SOL"],
["federalist-proxy.app.cloud.gov","FAS TTS/SOL"],
["federalist.18f.gov","FAS TTS/SOL"],
["federalistapp.18f.gov","FAS TTS/SOL"],
["federation.data.gov","FAS TTS/SOL"],
["fedidcard.gov","FAS ITC"],
["fedpay.gsa.gov","CFO"],
["fedramp.gov","FAS TTS/SOL"],
["fedsim.gsa.gov","FAS AAS"],
["fedspecs.gsa.gov","FAS R5"],
["feedback.usa.gov","FAS TTS/SOL"],
["fellows-in-innovation.pif.gov","FAS TTS/PIF"],
["ffms.fas.gsa.gov","FAS TTL"],
["files.18f.gov","FAS TTS/18F"],
["finance.ocfo.gsa.gov","GSA IT"],
["financeweb.gsa.gov","CFO"],
["fleet.fas.gsa.gov","FAS TTL"],
["fleet.gsa.gov","FAS TTL"],
["fleeteur.fas.gsa.gov","FAS TTL"],
["fmvrs.fas.gsa.gov","FAS TTL"],
["fpc.gov","OGP MY"],
["fpds.gov","FAS OSM/IAE"],
["fpki.idmanagement.gov","OGP ME"],
["frpg.gov","OGP MA"],
["fsd.gov","FAS OSM/IAE"],
["fsrs.gov","FAS OSM/IAE"],
["go.usa.gov","FAS TTS/SOL"],
["gsa.gov","OSC ZOD"],
["gsa.gov/fine-arts","PBS"],
["gsaadvantage.gov","FAS GSS"],
["gsaauctions.gov","FAS GSS"],
["gsaelibrary.gsa.gov","FAS MAS"],
["gsaglobalsupply.gsa.gov","FAS GSS"],
["gsaxcess.gov","FAS GSS"],
["gsaxcesspractice.fas.gsa.gov","FAS"],
["hallways.cap.gsa.gov","FAS OESM"],
["handbook.tts.gsa.gov","FAS TTS/SOL"],
["home.do.gov","OGP ME"],
["i14y.search.usa.gov","FAS TTS/SOL"],
["i14y.usa.gov","FAS TTS/SOL"],
["identity-dev-docs.18f.gov","FAS TTS/SOL"],
["idmanagement.gov","OGP ME"],
["insite.gsa.gov","OSC ZOD"],
["interact.gsa.gov","FAS CASE"],
["inventory.data.gov","FAS TTS/SOL"],
["itjobs.open.gsa.gov","GSA IT"],
["join.tts.gsa.gov","FAS TTS"],
["labs.gsa.gov","GSA IT"],
["labs.usa.gov","FAS TTS/SOL"],
["login.fr.cloud.gov","FAS TTS/SOL"],
["login.gov","FAS TTS/SOL"],
["lop.gsa.gov","GSA IT"],
["management.cio.gov","OGP MY"],
["markdown-helper.18f.gov","FAS TTS/18F"],
["marketplace.fedramp.gov","FAS TTS/SOL"],
["methods.18f.gov","FAS TTS/18F"],
["mobile.reginfo.gov","OGP MR"],
["mysales.fas.gsa.gov","FAS GSS"],
["mysmartplans.gsa.gov","PBS"],
["navigator.gsa.gov","FAS ESM"],
["ncrrecycles.gsa.gov/recycle/","PBS"],
["oasispet.gsa.gov/cpet/view","FAS ESM"],
["oes.gsa.gov","OGP MS"],
["open-staging.usa.gov","FAS TTS/SOL"],
["open.gsa.gov","GSA IT"],
["open.sam.gov",""],
["open.usa.gov","FAS TTS/SOL"],
["p3.cap.gsa.gov/gui","FAS ESM"],
["pacs.idmanagement.gov","OGP ME"],
["paygap.pif.gov","FAS TTS/PIF"],
["paymentaccuracy.gov","OGP MY"],
["performance.gov","OGP MY"],
["pic.gov","OGP MY"],
["piv.idmanagement.gov","OGP ME"],
["plainlanguage.gov","FAS TTS/SOL"],
["playbook.cio.gov","OGP MY"],
["pm.idmanagement.gov","OGP ME"],
["pra.digital.gov","FAS TTS/SOL"],
["presidentialinnovationfellows.gov","FAS TTS/PIF"],
["private-eye.18f.gov","FAS TTS/18F"],
["product-guide.18f.gov","FAS TTS/18F"],
["property.reporting.gov","OGP MA"],
["public-sans.digital.gov","FAS TTS/SOL"],
["realestatesales.gov/gsaauctions/gsaauctions/","PBS"],
["realpropertyprofile.gov","OGP MA"],
["reginfo.gov","OGP MR"],
["regulations.gov","OGP MR"],
["reporting.gov","OGP MA"],
["resources.data.gov","FAS TTS/SOL"],
["ret.gsa.gov","PBS"],
["rocis.gov","OGP MR"],
["sam.gov","FAS OSM/IAE"],
["sat.reginfo.gov","OGP"],
["sdg.data.gov","FAS TTS/SOL"],
["search.gov","FAS TTS/SOL"],
["section508.gov","OGP ME"],
["secure.login.gov","FAS TTS/SOL"],
["sftool.gov","OGP MG"],
["smartpay.gsa.gov","FAS PSHC"],
["str.gsa.gov","FAS TTL"],
["strategy.data.gov","FAS TTS/SOL"],
["tailored.fedramp.gov","FAS TTS/SOL"],
["tech.gsa.gov","GSA IT"],
["techfarhub.cio.gov","OGP MY"],
["tmf.cio.gov","OGP MY"],
["tophealth.pif.gov","FAS TTS/PIF"],
["touchpoints.digital.gov","FAS TTS/SOL"],
["training.rocis.gov",""],
["training.smartpay.gsa.gov","FAS"],
["travel.reporting.gov","OGP MA"],
["usa.gov","FAS TTS/SOL"],
["usability.gov","FAS TTS/SOL"],
["usaccess-alp.gsa.gov","FAS R5"],
["usdigitalregistry.digita.gov","FAS TTS/SOL"],
["usmcservmart.gsa.gov","FAS GSS"],
["ussm.gsa.gov","OGP MY"],
["vcss.ocfo.gsa.gov","GSA IT"],
["vec.gsa.gov","FAS MAS"],
["vehicledispatch.fas.gsa.gov","FAS TTL"],
["vehiclestd.fas.gsa.gov","FAS TTL"],
["vote.gov","FAS TTS/SOL"],
["vsc.gsa.gov","FAS MAS"],
["wp-bsp.data.gov","FAS TTS/SOL"],
["wdol.gov","FAS OSM/IAE"],
["wdolhome.sam.gov","FAS OSM/IAE"],
["portfolios.18f.gov","FAS TTS/18F"],
["ux-guide.18f.gov","FAS TTS/18F"],
["api.acquisition.gov","OGP MV"],
["login.acquisition.gov","OGP MV"],
["afadvantage.gov","FAS GSS"],
["advantage.gsa.gov","FAS GSS"],
["dhsadvantage.gsa.gov","FAS GSS"],
["gsaadvantage.gsa.gov","FAS GSS"],
["usdaadvantage.gsa.gov","FAS GSS"],
["vaadvantage.gsa.gov","FAS GSS"],
["courtsweb.gsa.gov","PBS"],
["design.login.gov","FAS TTS/SOL"],
["partners.login.gov","FAS TTS/SOL"],
["sam-landing.login.gov","FAS TTS/SOL"]
];

let siteListLength = siteList.length;
for (var i=0; i<siteListLength; i++) {
    (async () => {
        await captureWebsite.file('https://' + siteList[i][0], dir + '/' + siteList[i][1] + '_' + siteList[i][0] + '.png');
    })();
    i%3 ? "" : setTimeout(dummyfunction, 10000);
}

function dummyfunction() {}




