# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: EDX CLI Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'Tools/edxcli/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Tools/edxcli/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: create env file
      run: |
        touch .env
        echo "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> ./Tools/edxcli/.env
        echo "TOUCHPOINTS_API_KEY=${{ secrets.TOUCHPOINTS_API_KEY }}" >> ./Tools/edxcli/.env
    - name: Read .nvmrc
      working-directory: ./Tools/edxcli
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: yarn install --immutable
      working-directory: ./Tools/edxcli
    - run: yarn run build
      working-directory: ./Tools/edxcli
    - run: yarn test
      working-directory: ./Tools/edxcli